In [ ]:
import numpy as np

# 1. Empty array 2x2
empty_2x2 = np.empty((2,2))
print("Empty 2x2:\n", empty_2x2)

Empty 2x2:
 [[3.16696654e-315 0.00000000e+000]
 [9.88131292e-324             nan]]


In [ ]:
import numpy as np

ones_4x2 = np.ones((4,2))
print("\nOnes 4x2:\n", ones_4x2)


Ones 4x2:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
import numpy as np
filled_3x3 = np.full((3,3), 7)
print("\nFull 3x3 with 7:\n", filled_3x3)


Full 3x3 with 7:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]


In [ ]:
import numpy as np
sample = np.array([[1,2,3],[4,5,6]])
zeros_like_sample = np.zeros_like(sample)
print("\nZeros_like sample:\n", zeros_like_sample)



Zeros_like sample:
 [[0 0 0]
 [0 0 0]]


In [ ]:
ones_like_sample = np.ones_like(sample)
print("\nOnes_like sample:\n", ones_like_sample)


Ones_like sample:
 [[1 1 1]
 [1 1 1]]


In [ ]:
new_list = [1,2,3,4]
arr_from_list = np.array(new_list)
print("\nArray from list:\n", arr_from_list)


Array from list:
 [1 2 3 4]


problem 2

In [ ]:
import numpy as np

# 1. Array 10 to 49
arr_10_49 = np.arange(10,50)
print("Array 10..49:\n", arr_10_49)


Array 10..49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
# 2. 3x3 matrix 0..8
mat_3x3_0_8 = np.arange(9).reshape(3,3)
print("\n3x3 0..8:\n", mat_3x3_0_8)



3x3 0..8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
# 3. Identity matrix 3x3
eye_3 = np.eye(3)
print("\nIdentity 3x3:\n", eye_3)


Identity 3x3:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
# 4. Random array size 30 + mean
rand30 = np.random.random(30)
print("\nRandom 30 mean:", rand30.mean())


Random 30 mean: 0.5903156260195438


In [ ]:
# 5. Random 10x10 + min/max
rand10x10 = np.random.random((10,10))
print("\n10x10 min:", rand10x10.min(), "max:", rand10x10.max())


10x10 min: 0.015656784359714737 max: 0.9920338247246664


In [ ]:
# 6. Zero array size 10, replace 5th element
zeros_10 = np.zeros(10)
zeros_10[4] = 1
print("\nZeros array w/ 5th element=1:\n", zeros_10)



Zeros array w/ 5th element=1:
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [ ]:
# 7. Reverse array
arr = np.array([1,2,0,0,4,0])
print("\nReversed array:", arr[::-1])


Reversed array: [0 4 0 0 2 1]


In [ ]:
# 8. 2D array with border=1, inside=0
border = np.ones((5,5), dtype=int)
border[1:-1,1:-1] = 0
print("\nBorder pattern:\n", border)


Border pattern:
 [[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [ ]:
# 9. 8x8 checkerboard
checker = np.zeros((8,8), dtype=int)
checker[::2, ::2] = 1
checker[1::2, 1::2] = 1
print("\nCheckerboard:\n", checker)


Checkerboard:
 [[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


problem 3

In [ ]:
import numpy as np

x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

In [ ]:
 #1. Add
print("x + y:\n", x + y)

x + y:
 [[ 6  8]
 [10 13]]


In [ ]:
# 2. Subtract
print("\nx - y:\n", x - y)


x - y:
 [[-4 -4]
 [-4 -3]]


In [ ]:
# 3. Multiply by integer
print("\nx * 3:\n", x * 3)


x * 3:
 [[ 3  6]
 [ 9 15]]


In [ ]:
# 4. Square elements
print("\nx squared:\n", x**2)


x squared:
 [[ 1  4]
 [ 9 25]]


In [ ]:
# 5. Dot products
print("\ndot(v, w):", np.dot(v, w))
print("x dot v:", x.dot(v))
print("x dot y:\n", x.dot(y))



dot(v, w): 219
x dot v: [29 77]
x dot y:
 [[19 22]
 [50 58]]


In [ ]:
# 6. Concatenate x & y (rows), v & w (columns)
print("\nConcatenate x,y along rows:\n", np.concatenate((x,y), axis=0))
concat_vw = np.vstack((v, w)).T
print("\nConcatenate v & w as columns:\n", concat_vw)



Concatenate x,y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]

Concatenate v & w as columns:
 [[ 9 11]
 [10 12]]


In [ ]:
# 7. Why x and v cannot concatenate?
try:
    print(np.concatenate((x, v)))
except Exception as e:
    print("\nError concatenating x and v:\n", e)
    print("Reason: x is 2x2, v is 1D length-2. Their shapes do not match on axis 0.")


Error concatenating x and v:
 all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)
Reason: x is 2x2, v is 1D length-2. Their shapes do not match on axis 0.


problem 4


In [ ]:
import numpy as np

A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])


In [ ]:
# 1. A * A^-1 = I
A_inv = np.linalg.inv(A)
print("A inverse:\n", A_inv)
print("\nA * A^-1:\n", A.dot(A_inv))


A inverse:
 [[-2.    1.  ]
 [ 1.75 -0.75]]

A * A^-1:
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]


In [ ]:
# 2. AB != BA
AB = A.dot(B)
BA = B.dot(A)
print("\nAB:\n", AB)
print("\nBA:\n", BA)
print("AB == BA? ->", np.array_equal(AB, BA))



AB:
 [[23 13]
 [51 29]]

BA:
 [[36 44]
 [13 16]]
AB == BA? -> False


In [ ]:
# 3. (AB)^T = B^T A^T
lhs = (A.dot(B)).T
rhs = B.T.dot(A.T)
print("\n(AB)^T:\n", lhs)
print("\nB^T A^T:\n", rhs)
print("Equal? ->", np.array_equal(lhs, rhs))


(AB)^T:
 [[23 51]
 [13 29]]

B^T A^T:
 [[23 51]
 [13 29]]
Equal? -> True


In [ ]:
# 4. Solve system using matrix form
M = np.array([[2,-3,1],
              [1,-1,2],
              [3,1,-1]])

rhs = np.array([-1,-3,9])

solution = np.linalg.solve(M, rhs)
print("\nSolution using solve():\n", solution)


Solution using solve():
 [ 2.  1. -2.]


In [ ]:
# 5. Solve using inverse
solution_inv = np.linalg.inv(M).dot(rhs)
print("\nSolution using inverse:\n", solution_inv)


Solution using inverse:
 [ 2.  1. -2.]
